### ISSUE TITLE
Typo in grove_hightemperature_sensor.py

### ISSUE THREAD

**Issue by quasipickle** [RobertLucian/GrovePi#8]
Line 123: 
`value = value * mV + self.__sensor_table[2][step - 2]`

But the corresponding line in the source C++ file ( https://github.com/Seeed-Studio/Grove_HighTemp_Sensor/blob/master/Hight_Temp.cpp ) is:
 `value = mV * value + Var_VtoT_K[2][i-1];`

I'm not going to pretend to know what the significance of that is (if anything), but I did notice it.

**Comment by RobertLucian** [comment]
Hmm, good observation.

I think this is a bug and will appear at higher temperatures. Like in the range of 200-600 Celsius degrees.

I'll hold onto this one and test it.
